import type { Metadata } from "next";
import { Space_Grotesk, Righteous } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({ 
  subsets: ["latin"],
  weight: ["400", "700"],
});

const righteous = Righteous({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-righteous",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} ${righteous.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
